version: '3'

services:
  node:
    container_name: nodejs
    image: node:12
    ports:
      - '3000:3000'
    volumes:
      - ./:/srv/app
    working_dir: /srv/app
    command: 'npx nodemon index.js'
    